### ISSUE TITLE
Missing epub:type="se:name.publication.book" semantics

### ISSUE THREAD

**Issue by robinwhittleton** [RiceKrisBs/sax-rohmer_brood-of-the-witch-queen#5]
- <i>The Magus</i>
- <i>Book of the Dead</i>
- <i>Book of Thoth</i>
- <i>Papyrus Harris</i>
- <i>Ritual of the Dead</i>

**Comment by robinwhittleton** [comment]
Also _The Planet_ is either a newspaper or a magazine.

**Comment by RiceKrisBs** [comment]
Added "se:name.publication.book" for The Magus, Book of the Dead, Book of Thoth, Papyrus Harris, and Ritual of the Dead. Added "se:name.publication.newspaper" for The Planet.
